is_2d: false
boards:
{
    "tags": [
      {
        "ID": 1,
        "pose": {
          "translation": {
            "x": 0.0,
            "y": 3.892,
            "z": 1.661
          },
          "rotation": {
            "quaternion": {
              "W": 1.0,
              "X": 0.0,
              "Y": 0.0,
              "Z": 0.0
            }
          }
        }
      },
      {
        "ID": 2,
        "pose": {
          "translation": {
            "x": 0.0,
            "y": 2.020,
            "z": 0.753
          },
          "rotation": {
            "quaternion": {
              "W": 1.0,
              "X": 0.0,
              "Y": 0.0,
              "Z": 0.0
            }
          }
        }
      },
      {
        "ID": 3,
        "pose": {
          "translation": {
            "x": 0.0,
            "y": 3.628,
            "z": 0.758
          },
          "rotation": {
            "quaternion": {
              "W": 1.0,
              "X": 0.0,
              "Y": 0.0,
              "Z": 0.0
            }
          }
        }
      },
      {
        "ID": 4,
        "pose": {
          "translation": {
            "x": 0.0,
            "y": 4.159,
            "z": 0.748
          },
          "rotation": {
            "quaternion": {
              "W": 1.0,
              "X": 0.0,
              "Y": 0.0,
              "Z": 0.0
            }
          }
        }
      },
      {
        "ID": 5,
        "pose": {
          "translation": {
            "x": 0.0,
            "y": 5.755,
            "z": 0.746
          },
          "rotation": {
            "quaternion": {
              "W": 1.0,
              "X": 0.0,
              "Y": 0.0,
              "Z": 0.0
            }
          }
        }
      },
      {
        "ID": 6,
        "pose": {
          "translation": {
            "x": 4.860,
            "y": 8.293,
            "z": 1.206
          },
          "rotation": {
            "quaternion": {
              "W": -0.7071067811865475,
              "X": 0.0,
              "Y": 0.0,
              "Z": 0.7071067811865476
            }
          }
        }
      },
      {
        "ID": 7,
        "pose": {
          "translation": {
            "x": 6.076,
            "y": 8.293,
            "z": 1.220
          },
          "rotation": {
            "quaternion": {
                "W": -0.7071067811865475,
                "X": 0.0,
                "Y": 0.0,
                "Z": 0.7071067811865476
            }
          }
        }
      },
      {
        "ID": 8,
        "pose": {
          "translation": {
            "x": 7.318,
            "y": 8.293,
            "z": 1.209
          },
          "rotation": {
            "quaternion": {
                "W": -0.7071067811865475,
                "X": 0.0,
                "Y": 0.0,
                "Z": 0.7071067811865476
            }
          }
        }
      },
      {
        "ID": 9,
        "pose": {
          "translation": {
            "x": 8.531,
            "y": 8.293,
            "z": 1.208
          },
          "rotation": {
            "quaternion": {
                "W": -0.7071067811865475,
                "X": 0.0,
                "Y": 0.0,
                "Z": 0.7071067811865476
            }
          }
        }
      },
      {
        "ID": 10,
        "pose": {
          "translation": {
            "x": -0.905,
            "y": 7.29,
            "z": 1.547
          },
          "rotation": {
            "quaternion": {
              "W": 1.0,
              "X": 0.0,
              "Y": 0.0,
              "Z": 0.0
            }
          }
        }
      },
      {
        "ID": 11,
        "pose": {
          "translation": {
            "x": -0.905,
            "y": 7.29,
            "z": 0.974
          },
          "rotation": {
            "quaternion": {
              "W": 1.0,
              "X": 0.0,
              "Y": 0.0,
              "Z": 0.0
            }
          }
        }
      },
      {
        "ID": 12,
        "pose": {
          "translation": {
            "x": 10.865,
            "y": 7.086,
            "z": 1.424
          },
          "rotation": {
            "quaternion": {
              "W": 0.0,
              "X": 0.0,
              "Y": 0.0,
              "Z": 1.0
            }
          }
        }
      },
      {
        "ID": 13,
        "pose": {
          "translation": {
            "x": 10.865,
            "y": 5.958,
            "z": 1.343
          },
          "rotation": {
            "quaternion": {
              "W": 0.0,
              "X": 0.0,
              "Y": 0.0,
              "Z": 1.0
            }
          }
        }
      },
      {
        "ID": 14,
        "pose": {
          "translation": {
            "x": 10.865,
            "y": 0.216,
            "z": 1.403
          },
          "rotation": {
            "quaternion": {
              "W": 0.0,
              "X": 0.0,
              "Y": 0.0,
              "Z": 1.0
            }
          }
        }
      },
      {
        "ID": 15,
        "pose": {
          "translation": {
            "x": 8.104,
            "y": -1.850,
            "z": 1.785
          },
          "rotation": {
            "quaternion": {
                "W": 0.7071067811865475,
                "X": 0.0,
                "Y": 0.0,
                "Z": 0.7071067811865476
            }
          }
        }
      },
      {
        "ID": 16,
        "pose": {
          "translation": {
            "x": 2.89,
            "y": -1.850,
            "z": 1.408
          },
          "rotation": {
            "quaternion": {
                "W": 0.7071067811865475,
                "X": 0.0,
                "Y": 0.0,
                "Z": 0.7071067811865476
            }
          }
        }
      }
    ],
    "field": {
      "length": 10.865,
      "width": 8.293
    }
  }
  world:
  - ID: 1
    marker_size: 0.1651
    pose:
      rotation:
        w: -0.6830127018922194
        x: 0.6830127018922194
        y: 0.18301270189221924
        z: -0.18301270189221924
      translation:
        x: 15.079471999999997
        y: 0.24587199999999998
        z: 1.355852
  - ID: 2
    marker_size: 0.1651
    pose:
      rotation:
        w: -0.6830127018922194
        x: 0.6830127018922194
        y: 0.18301270189221924
        z: -0.18301270189221924
      translation:
        x: 16.185134
        y: 0.883666
        z: 1.355852
  - ID: 3
    marker_size: 0.1651
    pose:
      rotation:
        w: -0.5000000000000001
        x: 0.5000000000000001
        y: 0.5
        z: -0.5
      translation:
        x: 16.579342
        y: 4.982717999999999
        z: 1.4511020000000001
  - ID: 4
    marker_size: 0.1651
    pose:
      rotation:
        w: -0.5000000000000001
        x: 0.5000000000000001
        y: 0.5
        z: -0.5
      translation:
        x: 16.579342
        y: 5.547867999999999
        z: 1.4511020000000001
  - ID: 5
    marker_size: 0.1651
    pose:
      rotation:
        w: -5.551115123125784e-17
        x: 5.551115123125784e-17
        y: 0.7071067811865476
        z: -0.7071067811865476
      translation:
        x: 14.700757999999999
        y: 8.2042
        z: 1.355852
  - ID: 6
    marker_size: 0.1651
    pose:
      rotation:
        w: -5.551115123125784e-17
        x: 5.551115123125784e-17
        y: 0.7071067811865476
        z: -0.7071067811865476
      translation:
        x: 1.8415
        y: 8.2042
        z: 1.355852
  - ID: 7
    marker_size: 0.1651
    pose:
      rotation:
        w: -0.5
        x: 0.5
        y: -0.5
        z: 0.5
      translation:
        x: -0.038099999999999995
        y: 5.547867999999999
        z: 1.4511020000000001
  - ID: 8
    marker_size: 0.1651
    pose:
      rotation:
        w: -0.5
        x: 0.5
        y: -0.5
        z: 0.5
      translation:
        x: -0.038099999999999995
        y: 4.982717999999999
        z: 1.4511020000000001
  - ID: 9
    marker_size: 0.1651
    pose:
      rotation:
        w: -0.6830127018922193
        x: 0.6830127018922193
        y: -0.18301270189221938
        z: 0.18301270189221938
      translation:
        x: 0.356108
        y: 0.883666
        z: 1.355852
  - ID: 10
    marker_size: 0.1651
    pose:
      rotation:
        w: -0.6830127018922193
        x: 0.6830127018922193
        y: -0.18301270189221938
        z: 0.18301270189221938
      translation:
        x: 1.4615159999999998
        y: 0.24587199999999998
        z: 1.355852
  - ID: 11
    marker_size: 0.1651
    pose:
      rotation:
        w: 0.18301270189221938
        x: -0.18301270189221938
        y: 0.6830127018922193
        z: -0.6830127018922193
      translation:
        x: 11.904726
        y: 3.7132259999999997
        z: 1.3208
  - ID: 12
    marker_size: 0.1651
    pose:
      rotation:
        w: -0.6830127018922193
        x: 0.6830127018922193
        y: -0.18301270189221938
        z: 0.18301270189221938
      translation:
        x: 11.904726
        y: 4.49834
        z: 1.3208
  - ID: 13
    marker_size: 0.1651
    pose:
      rotation:
        w: -0.5000000000000001
        x: 0.5000000000000001
        y: 0.5
        z: -0.5
      translation:
        x: 11.220196
        y: 4.105148
        z: 1.3208
  - ID: 14
    marker_size: 0.1651
    pose:
      rotation:
        w: -0.5
        x: 0.5
        y: -0.5
        z: 0.5
      translation:
        x: 5.320792
        y: 4.105148
        z: 1.3208
  - ID: 15
    marker_size: 0.1651
    pose:
      rotation:
        w: -0.6830127018922194
        x: 0.6830127018922194
        y: 0.18301270189221924
        z: -0.18301270189221924
      translation:
        x: 4.641342
        y: 4.49834
        z: 1.3208
  - ID: 16
    marker_size: 0.1651
    pose:
      rotation:
        w: -0.1830127018922195
        x: 0.1830127018922195
        y: 0.6830127018922193
        z: -0.6830127018922193
      translation:
        x: 4.641342
        y: 3.7132259999999997
        z: 1.3208
