<?xml version="1.0"?>
<package format="3">
  <name>v4l2_camera</name>
  <version>0.1.0</version>
  <description>Custom ROS 2 node for capturing video frames using V4L2 with explicit resolution control.</description>

  <maintainer email="collincresta1386@gmail.com">Collin Cresta</maintainer>
  <license>BSD-2-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Core Dependencies -->
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>image_transport</depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

  <!-- System dependencies -->
  <exec_depend>opencv</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
