image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [544.56192,   0.     , 320.12796,
           0.     , 545.35631, 234.91248,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.051016, -0.068020, -0.000310, 0.000851, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [549.83427,   0.     , 320.61837,   0.     ,
           0.     , 550.96502, 234.78423,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]